<html><body><div><article class="markdown-body entry-content" itemprop="text"><h1><a id="user-content-the-pappy-proxy" class="anchor" href="#the-pappy-proxy" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>The Pappy Proxy</h1>

<p><a href="https://roglew.github.io/pappy-proxy/">Documentation</a> - <a href="https://roglew.github.io/pappy-proxy/tutorial.html">Tutorial</a></p>

<h2><a id="user-content-introduction" class="anchor" href="#introduction" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Introduction</h2>

<p>The Pappy (<strong>P</strong>roxy <strong>A</strong>ttack <strong>P</strong>roxy <strong>P</strong>rox<strong>Y</strong>) Proxy is an intercepting proxy for performing web application security testing. Its features are often similar, or straight up rippoffs from <a href="https://portswigger.net/burp/">Burp Suite</a>. However, Burp Suite is neither open source nor a command line tool, thus making a proxy like Pappy inevitable. The project is still in its early stages, so there are bugs and only the bare minimum features, but it can already do some cool stuff.</p>

<h2><a id="user-content-contributing" class="anchor" href="#contributing" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Contributing</h2>

<p><strong>I am taking any and all feature requests.</strong> If you've used Burp and had any inconvenience with it, tell me about it and I'll do everything in my power to make sure Pappy doesn't have those issues. Or even better, if you want Burp to do something that it doesn't already, let me know so that I can <del>use it to stomp them into the dust</del> improve my project.</p>

<p>If you're brave and want to try and contribute code, please let me know. Right now the codebase is kind of rough and I have refactored it a few times already, but I would be more than happy to find a stable part of the codebase that you can contribute to.</p>

<p>Another option is to try writing a plugin. It might be a bit easier than contributing code and plugins are extremely easy to integrate as a core feature. So you can also contribute by writing a plugin and letting me know about it. You can find out more by looking at <a href="https://roglew.github.io/pappy-proxy/pappyplugins.html">the official plugin docs</a>.</p>

<p>You can find ideas for features to add on <a href="https://roglew.github.io/pappy-proxy/contributing.html">the contributing page in the docs</a>.</p>

<h1><a id="user-content-how-to-use-it" class="anchor" href="#how-to-use-it" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>How to Use It</h1>

<h2><a id="user-content-installation" class="anchor" href="#installation" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Installation</h2>

<p>Pappy supports OS X and Linux (sorry Windows). Installation requires <code>pip</code> or some other command that can handle a <code>setup.py</code> with requirements. Once the requirements are installed, you can check that it installed correctly by running <code>pappy -l</code> to start the proxy.</p>

<pre><code>$ git clone --recursive https://github.com/roglew/pappy-proxy.git
$ cd pappy-proxy
$ pip install .
</code></pre>

<h2><a id="user-content-quickstart" class="anchor" href="#quickstart" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Quickstart</h2>

<p>Pappy projects take up an entire directory. Any generated scripts, exported responses, plugin data, etc. will be placed in the current directory so it's good to give your project a directory of its own. To start a project, do something like:</p>

<pre><code>$ mkdir test_project
$ cd test_project 
$ pappy
Copying default config to directory
Proxy is listening on port 8000
pappy&gt; exit
$ ls
data.db      project_config.json
$ 
</code></pre>

<p>And that's it! The proxy will by default be running on port 8000 and bound to localhost (to keep the hackers out). You can modify the port/interface in <code>config.json</code>. You can list all your intercepted requests with <code>ls</code>, view a full request with <code>vfq &lt;reqid&gt;</code> or view a full response with <code>vfs &lt;reqid&gt;</code>. Right now, the only command to delete requests is <code>filter_prune</code> which deletes all the requests that aren't in the current context (look at the sections on the context/filter strings for more information on that).</p>

<h2><a id="user-content-lite-mode" class="anchor" href="#lite-mode" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Lite Mode</h2>

<p>If you don't want to dirty up a directory, you can run Pappy in "lite" mode. Pappy will use the default configuration settings and will create a temporary data file in <code>/tmp</code> to use. When you quit, the file will be deleted. If you want to run Pappy in lite mode, run Pappy with either <code>-l</code> or <code>--lite</code>.</p>

<p>Example:</p>

<pre><code>$ pappy -l
Temporary datafile is /tmp/tmpw4mGv2
Proxy is listening on port 8000
pappy&gt; quit
Deleting temporary datafile
$ 
</code></pre>

<h2><a id="user-content-adding-the-ca-cert-to-your-browser" class="anchor" href="#adding-the-ca-cert-to-your-browser" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Adding The CA Cert to Your Browser</h2>

<p>In order for Pappy to view data sent using HTTPS, you need to add a generated CA cert (<code>certificate.crt</code>) to your browser. Certificates are generated using the <code>gencerts</code> command and are by default stored in <code>~/.pappy/certs</code>. This allows Pappy to act as a CA and sign any HTTPS certificate it wants without the browser complaining. This allows Pappy to decrypt and modify HTTPS requests. The certificate installation instructions are different for each browser.</p>

<h3><a id="user-content-firefox" class="anchor" href="#firefox" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Firefox</h3>

<p>You can add the CA cert to Firefox by going to <code>Preferences -&gt; Advanced -&gt; View Certificates -&gt; Authorities -&gt; Import</code> and selecting the <code>certificate.crt</code> file in the <code>certs</code> directory.</p>

<h3><a id="user-content-chrome" class="anchor" href="#chrome" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Chrome</h3>

<p>You can add the CA cert to Chrome by going to <code>Settings -&gt; Show advanced settings -&gt; HTTPS/SSL -&gt; Manage Certificates -&gt; Authorities -&gt; Import</code> and selecting the <code>certificate.crt</code> file in the <code>certs</code> directory.</p>

<h3><a id="user-content-safari" class="anchor" href="#safari" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Safari</h3>

<p>For Safari (on macs, obviously), you need to add the CA cert to your system keychain. You can do this by double clicking on the CA cert and following the prompts.</p>

<h3><a id="user-content-internet-explorer" class="anchor" href="#internet-explorer" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Internet Explorer</h3>

<p>I didn't search too hard for instructions on this (since Pappy doesn't support windows) and I don't own a Windows machine to try this, so if you have trouble, I'm not the one to ask. According to Google you can double-click the cert to install it to the system, or you can do <code>Tools -&gt; Content -&gt; Certificates -&gt; Trusted Root Certificates -&gt; Import</code>.</p>

<h2><a id="user-content-configuration" class="anchor" href="#configuration" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Configuration</h2>

<p>Configuration for each project is done in the <code>config.json</code> file. The file is a JSON-formatted dictionary that contains settings for the proxy. The following fields can be used to configure the proxy:</p>

<table><thead>
<tr>
<th align="left">Key</th>
<th align="left">Value</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>data_file</code></td>
<td align="left">The file where requests and images will be stored</td>
</tr>
<tr>
<td align="left"><code>debug_dir</code> (optional)</td>
<td align="left">Where connection debug info should be stored. If not present, debug info is not saved to a file.</td>
</tr>
<tr>
<td align="left"><code>cert_dir</code></td>
<td align="left">Where the CA cert and the private key for the CA cert are stored</td>
</tr>
<tr>
<td align="left"><code>proxy_listeners</code></td>
<td align="left">A list of dicts which describe which ports the proxy will listen on. Each item is a dict with "port" and "interface" values which determine which port and interface to listen on. For example, if port=8000 and the interface is 127.0.0.1, the proxy will only accept connections from localhost on port 8000. To accept connections from anywhere, set the interface to 0.0.0.0.</td>
</tr>
</tbody></table>

<p>The following tokens will also be replaced with values:</p>

<table><thead>
<tr>
<th align="left">Token</th>
<th align="left">Replaced with</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>{DATADIR}</code></td>
<td align="left">The directory where Pappy's data files are stored</td>
</tr>
</tbody></table>

<p>See the default <code>config.json</code> for examples.</p>

<h2><a id="user-content-general-console-techniques" class="anchor" href="#general-console-techniques" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>General Console Techniques</h2>

<p>There are a few tricks you can use in general when using Pappy's console. Most of these are provided by the <a href="https://docs.python.org/2/library/cmd.html">cmd</a> and <a href="https://pythonhosted.org/cmd2/index.html">cmd2</a>.</p>

<h3><a id="user-content-run-a-shell-command" class="anchor" href="#run-a-shell-command" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Run a shell command</h3>

<p>You can run a shell command with <code>!</code>:</p>

<pre><code>pappy&gt; ls
ID  Verb  Host         Path               S-Code            Req Len  Rsp Len  Time  Mngl
5   GET   vitaly.sexy  /netscape.gif      304 Not Modified  0        0        0.08  --
4   GET   vitaly.sexy  /esr1.jpg          304 Not Modified  0        0        0.07  --
3   GET   vitaly.sexy  /construction.gif  304 Not Modified  0        0        0.07  --
2   GET   vitaly.sexy  /vitaly2.jpg                         0        N/A      --    --
1   GET   vitaly.sexy  /                  304 Not Modified  0        0        0.07  --
pappy&gt; !ls
cmdhistory  config.json  data.db
pappy&gt;
</code></pre>

<h3><a id="user-content-running-python-code" class="anchor" href="#running-python-code" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Running Python Code</h3>

<p>You can use the <code>py</code> command to either run python code or to drop down to a Python shell.</p>

<pre><code>pappy&gt; py print ':D '*10
:D :D :D :D :D :D :D :D :D :D
pappy&gt; py
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(ProxyCmd)

        py &lt;command&gt;: Executes a Python command.
        py: Enters interactive Python mode.
        End with ``Ctrl-D`` (Unix) / ``Ctrl-Z`` (Windows), ``quit()``, '`exit()``.
        Non-python commands can be issued with ``cmd("your command")``.
        Run python code from external files with ``run("filename.py")``

&gt;&gt;&gt; from pappyproxy import config
&gt;&gt;&gt; config.CONFIG_DICT
{u'data_file': u'./data.db', u'history_size': 1000, u'cert_dir': u'{DATADIR}/certs', u'proxy_listeners': [{u'interface': u'127.0.0.1', u'port': 8000}]}
&gt;&gt;&gt; exit()
pappy&gt;
</code></pre>

<h3><a id="user-content-redirect-output-to-file" class="anchor" href="#redirect-output-to-file" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Redirect Output To File</h3>

<p>You can use <code>&gt;</code> to direct output to a file. However, a number of commands use colored output. If you just redirect these to a file, there will be additional bytes which represent the ANSI color codes. To get around this, use the <code>nocolor</code> command to remove the color from the command output.</p>

<pre><code>pappy&gt; ls &gt; ls.txt
pappy&gt; !xxd -c 32 -g 4 ls.txt
0000000: 1b5b316d 1b5b346d 49442020 56657262 2020486f 73742020 20202020 20202050  .[1m.[4mID  Verb  Host         P
0000020: 61746820 20202020 20202020 20202020 2020532d 436f6465 20202020 20202020  ath               S-Code
0000040: 20202020 52657120 4c656e20 20527370 204c656e 20205469 6d652020 20204d6e      Req Len  Rsp Len  Time    Mn
0000060: 676c2020 1b5b306d 0a352020 201b5b33 366d4745 541b5b30 6d202020 1b5b3931  gl  .[0m.5   .[36mGET.[0m   .[91
0000080: 6d766974 616c792e 73657879 1b5b306d 20201b5b 33366d1b 5b306d2f 1b5b3334  mvitaly.sexy.[0m  .[36m.[0m/.[34
00000a0: 6d6e6574 73636170 652e6769 661b5b30 6d202020 2020201b 5b33356d 33303420  mnetscape.gif.[0m      .[35m304
00000c0: 4e6f7420 4d6f6469 66696564 1b5b306d 20203020 20202020 20202030 20202020  Not Modified.[0m  0        0
00000e0: 20202020 302e3038 20202020 2d2d2020 20200a34 2020201b 5b33366d 4745541b      0.08    --    .4   .[36mGET.
0000100: 5b306d20 20201b5b 39316d76 6974616c 792e7365 78791b5b 306d2020 1b5b3336  [0m   .[91mvitaly.sexy.[0m  .[36
0000120: 6d1b5b30 6d2f1b5b 33346d65 7372312e 6a70671b 5b306d20 20202020 20202020  m.[0m/.[34mesr1.jpg.[0m
0000140: 201b5b33 356d3330 34204e6f 74204d6f 64696669 65641b5b 306d2020 30202020   .[35m304 Not Modified.[0m  0
0000160: 20202020 20302020 20202020 2020302e 30372020 20202d2d 20202020 0a332020       0        0.07    --    .3
0000180: 201b5b33 366d4745 541b5b30 6d202020 1b5b3931 6d766974 616c792e 73657879   .[36mGET.[0m   .[91mvitaly.sexy
00001a0: 1b5b306d 20201b5b 33366d1b 5b306d2f 1b5b3334 6d636f6e 73747275 6374696f  .[0m  .[36m.[0m/.[34mconstructio
00001c0: 6e2e6769 661b5b30 6d20201b 5b33356d 33303420 4e6f7420 4d6f6469 66696564  n.gif.[0m  .[35m304 Not Modified
00001e0: 1b5b306d 20203020 20202020 20202030 20202020 20202020 302e3037 20202020  .[0m  0        0        0.07
0000200: 2d2d2020 20200a32 2020201b 5b33366d 4745541b 5b306d20 20201b5b 39316d76  --    .2   .[36mGET.[0m   .[91mv
0000220: 6974616c 792e7365 78791b5b 306d2020 1b5b3336 6d1b5b30 6d2f1b5b 33346d76  italy.sexy.[0m  .[36m.[0m/.[34mv
0000240: 6974616c 79322e6a 70671b5b 306d2020 20202020 201b5b33 366d3230 30204f4b  italy2.jpg.[0m       .[36m200 OK
0000260: 1b5b306d 20202020 20202020 20202020 30202020 20202020 20323033 34303033  .[0m            0        2034003
0000280: 20203135 352e3131 20202d2d 20202020 0a312020 201b5b33 366d4745 541b5b30    155.11  --    .1   .[36mGET.[0
00002a0: 6d202020 1b5b3931 6d766974 616c792e 73657879 1b5b306d 20201b5b 33366d1b  m   .[91mvitaly.sexy.[0m  .[36m.
00002c0: 5b306d2f 1b5b3334 6d1b5b30 6d202020 20202020 20202020 20202020 2020201b  [0m/.[34m.[0m                  .
00002e0: 5b33356d 33303420 4e6f7420 4d6f6469 66696564 1b5b306d 20203020 20202020  [35m304 Not Modified.[0m  0
0000300: 20202030 20202020 20202020 302e3037 20202020 2d2d2020 20200a                0        0.07    --    .
pappy&gt; nocolor ls &gt; ls2.txt
pappy&gt; !xxd -c 32 -g 4 ls2.txt
0000000: 49442020 56657262 2020486f 73742020 20202020 20202050 61746820 20202020  ID  Verb  Host         Path
0000020: 20202020 20202020 2020532d 436f6465 20202020 20202020 20202020 52657120            S-Code            Req
0000040: 4c656e20 20527370 204c656e 20205469 6d652020 20204d6e 676c2020 0a352020  Len  Rsp Len  Time    Mngl  .5
0000060: 20474554 20202076 6974616c 792e7365 78792020 2f6e6574 73636170 652e6769   GET   vitaly.sexy  /netscape.gi
0000080: 66202020 20202033 3034204e 6f74204d 6f646966 69656420 20302020 20202020  f      304 Not Modified  0
00000a0: 20203020 20202020 20202030 2e303820 2020202d 2d202020 200a3420 20204745    0        0.08    --    .4   GE
00000c0: 54202020 76697461 6c792e73 65787920 202f6573 72312e6a 70672020 20202020  T   vitaly.sexy  /esr1.jpg
00000e0: 20202020 33303420 4e6f7420 4d6f6469 66696564 20203020 20202020 20202030      304 Not Modified  0        0
0000100: 20202020 20202020 302e3037 20202020 2d2d2020 20200a33 20202047 45542020          0.07    --    .3   GET
0000120: 20766974 616c792e 73657879 20202f63 6f6e7374 72756374 696f6e2e 67696620   vitaly.sexy  /construction.gif
0000140: 20333034 204e6f74 204d6f64 69666965 64202030 20202020 20202020 30202020   304 Not Modified  0        0
0000160: 20202020 20302e30 37202020 202d2d20 2020200a 32202020 47455420 20207669       0.07    --    .2   GET   vi
0000180: 74616c79 2e736578 7920202f 76697461 6c79322e 6a706720 20202020 20203230  taly.sexy  /vitaly2.jpg       20
00001a0: 30204f4b 20202020 20202020 20202020 30202020 20202020 20323033 34303033  0 OK            0        2034003
00001c0: 20203135 352e3131 20202d2d 20202020 0a312020 20474554 20202076 6974616c    155.11  --    .1   GET   vital
00001e0: 792e7365 78792020 2f202020 20202020 20202020 20202020 20202033 3034204e  y.sexy  /                  304 N
0000200: 6f74204d 6f646966 69656420 20302020 20202020 20203020 20202020 20202030  ot Modified  0        0        0
0000220: 2e303720 2020202d 2d202020 200a0a                                        .07    --    ..
pappy&gt;
</code></pre>

<p>If you want to write the contents of a request or response to a file, don't use <code>nocolor</code> with <code>vfq</code> or <code>vfs</code>. Use just the <code>vbq</code> or <code>vbs</code> commands.</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>nocolor</code></td>
<td align="left">Run a command and print its output without ASCII escape codes. Intended for use when redirecting output to a file. Should only be used with text and not with binary data.</td>
</tr>
</tbody></table>

<h2><a id="user-content-generating-pappys-ca-cert" class="anchor" href="#generating-pappys-ca-cert" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Generating Pappy's CA Cert</h2>

<p>In order to intercept and modify requests to sites that use HTTPS, you have to generate and install CA certs to your browser. You can do this by running the <code>gencerts</code> command in Pappy. By default, certs are stored <code>~/.pappy/certs</code>. This is also the default location that Pappy will look for certificates (unless you specify otherwise in <code>config.json</code>.) In addition, you can give the <code>gencerts</code> command an argument to have it put the generated certs in a different directory.</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>gencerts [/path/to/put/certs/in]</code></td>
<td align="left">Generate a CA cert that can be added to your browser to let Pappy decrypt HTTPS traffic. Also generates the private key for that cert in the same directory. If no path is given, the certs will be placed in the default certificate location. Overwrites any existing certs.</td>
</tr>
</tbody></table>

<h2><a id="user-content-browsing-recorded-requestsresponses" class="anchor" href="#browsing-recorded-requestsresponses" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Browsing Recorded Requests/Responses</h2>

<p>The following commands can be used to view requests and responses</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>ls [a|&lt;num&gt;</code>]</td>
<td align="left">list, ls</td>
<td align="left">List requests that are in the current context (see Context section). Has information like the host, target path, and status code. With no arguments, it will print the 25 most recent requests in the current context. If you pass 'a' or 'all' as an argument, it will print all the requests in the current context. If you pass a number "n" as an argument, it will print the n most recent requests in the current context.</td>
</tr>
<tr>
<td align="left"><code>sm</code> [p]</td>
<td align="left">sm, site_map</td>
<td align="left">Print a tree showing the site map. It will display all requests in the current context that did not have a 404 response. This has to go through all of the requests in the current context so it may be slow. If the <code>p</code> option is given, it will print the paths as paths rather than as a tree.</td>
</tr>
<tr>
<td align="left"><code>viq &lt;id(s)&gt;</code></td>
<td align="left">view_request_info, viq</td>
<td align="left">View additional information about requests. Includes the target port, if SSL was used, applied tags, and other information.</td>
</tr>
<tr>
<td align="left"><code>vfq &lt;id(s)&gt;</code></td>
<td align="left">view_full_request, vfq, kjq</td>
<td align="left">[V]iew [F]ull Re[Q]uest, prints the full request including headers and data.</td>
</tr>
<tr>
<td align="left"><code>vbq &lt;id(s)&gt;</code></td>
<td align="left">view_request_bytes, vbq</td>
<td align="left">[V]iew [B]ytes of Re[Q]uest, prints the full request including headers and data without coloring or additional newlines. Use this if you want to write a request to a file.</td>
</tr>
<tr>
<td align="left"><code>ppq &lt;format&gt; &lt;id(s)&gt;</code></td>
<td align="left">pretty_print_request, ppq</td>
<td align="left">Pretty print a request with a specific format. See the table below for a list of formats.</td>
</tr>
<tr>
<td align="left"><code>vhq &lt;id(s)&gt;</code></td>
<td align="left">view_request_headers, vhq</td>
<td align="left">[V]iew [H]eaders of a Re[Q]uest. Prints just the headers of a request.</td>
</tr>
<tr>
<td align="left"><code>vfs &lt;id(s)&gt;</code></td>
<td align="left">view_full_response, vfs, kjs</td>
<td align="left">[V]iew [F]ull Re[S]ponse, prints the full response associated with a request including headers and data.</td>
</tr>
<tr>
<td align="left"><code>vhs &lt;id(s)&gt;</code></td>
<td align="left">view_response_headers, vhs</td>
<td align="left">[V]iew [H]eaders of a Re[S]ponse. Prints just the headers of a response associated with a request.</td>
</tr>
<tr>
<td align="left"><code>vbs &lt;id(s)&gt;</code></td>
<td align="left">view_response_bytes, vbs</td>
<td align="left">[V]iew [B]ytes of Re[S]ponse, prints the full response including headers and data without coloring or additional newlines. Use this if you want to write a response to a file.</td>
</tr>
<tr>
<td align="left"><code>pps &lt;format&gt; &lt;id(s)&gt;</code></td>
<td align="left">pretty_print_response, pps</td>
<td align="left">Pretty print a response with a specific format. See the table below for a list of formats.</td>
</tr>
<tr>
<td align="left"><code>pprm &lt;id(s)&gt;</code></td>
<td align="left">print_params, pprm</td>
<td align="left">Print a summary of the parameters submitted with the request. It will include URL params, POST params, and/or cookies</td>
</tr>
<tr>
<td align="left"><code>pri [ct] [key(s)] | param_info, pri | Print a summary of the parameters and values submitted by in-context requests. You can pass in keys to limit which values will be shown. If you also provide</code>ct` as the first argument, it will include any keys that are passed as arguments.</td>
<td align="left"/>
<td align="left"/>
</tr>
<tr>
<td align="left"><code>watch</code></td>
<td align="left">watch</td>
<td align="left">Print requests and responses in real time as they pass through the proxy.</td>
</tr>
</tbody></table>

<p>Available formats for <code>ppq</code> and <code>pps</code> commands:</p>

<table><thead>
<tr>
<th align="left">Format</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>form</code></td>
<td align="left">Print POST data submitted from a form (normal post data)</td>
</tr>
<tr>
<td align="left"><code>json</code></td>
<td align="left">Print as JSON</td>
</tr>
</tbody></table>

<p>The table shown by <code>ls</code> will have the following columns:</p>

<table><thead>
<tr>
<th align="left">Label</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left">ID</td>
<td align="left">The request ID of that request. Used to identify the request for other commands.</td>
</tr>
<tr>
<td align="left">Method</td>
<td align="left">The method(/http verb) for the request</td>
</tr>
<tr>
<td align="left">Host</td>
<td align="left">The host that the request was sent to</td>
</tr>
<tr>
<td align="left">Path</td>
<td align="left">The path of the request</td>
</tr>
<tr>
<td align="left">S-Code</td>
<td align="left">The status code of the response</td>
</tr>
<tr>
<td align="left">Req Len</td>
<td align="left">The length of the data submitted</td>
</tr>
<tr>
<td align="left">Rsp Len</td>
<td align="left">The length of the data returned in the response</td>
</tr>
<tr>
<td align="left">Time</td>
<td align="left">The time in seconds it took to complete the request</td>
</tr>
<tr>
<td align="left">Mngl</td>
<td align="left">If the request or response were mangled with the interceptor. If the request was mangled, the column will show 'q'. If the response was mangled, the column will show 's'. If both were mangled, it will show 'q/s'.</td>
</tr>
</tbody></table>

<h2><a id="user-content-tags" class="anchor" href="#tags" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Tags</h2>

<p>You can apply tags to a request and use filters to view specific tags. The following commands can be used to apply and remove tags to requests:</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>tag &lt;tag&gt; [id(s)]</code></td>
<td align="left">tag</td>
<td align="left">Apply a tag to the given requests. If no IDs are given, the tag will be applied to all in-context requests.</td>
</tr>
<tr>
<td align="left"><code>untag &lt;tag&gt; [id(s)]</code></td>
<td align="left">untag</td>
<td align="left">Remove a tag from the given ids. If no IDs are given, the tag is removed from every in-context request.</td>
</tr>
<tr>
<td align="left"><code>clrtag &lt;id(s)&gt;</code></td>
<td align="left">clrtag</td>
<td align="left">Removes all tags from the given ids.</td>
</tr>
</tbody></table>

<h2><a id="user-content-request-ids" class="anchor" href="#request-ids" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Request IDs</h2>

<p>Request IDs are how you identify a request and every command that involves specifying a request will take one or more request IDs. You can see it when you run <code>ls</code>. In addition, you can prepend an ID with prefixes to get requests or responses associated with the request (for example if you modified the request or its response with the interceptor, you can get the unmangled versions.) Here are the valid prefixes:</p>

<table><thead>
<tr>
<th align="left">Prefix</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>u</code></td>
<td align="left">If the request was mangled, prefixing the ID with <code>u</code> will result in the unmangled version of the request. The resulting request will not have an associated response because it was never submitted to the server.</td>
</tr>
<tr>
<td align="left"><code>s</code></td>
<td align="left">If the response was mangled, prefixing the request ID <code>s</code> will result in the same request but its associated response will be the unmangled version.</td>
</tr>
</tbody></table>

<p>I know it sounds kind of unintuitive. Here are some example commands that will hopefully make things clearer. Suppose request 1 had its request mangled, and request 2 had its response mangled.</p>

<ul>
<li><code>vfq 1</code> Prints the mangled version of request 1</li>
<li><code>vfq u1</code> Prints the unmangled version of request 1</li>
<li><code>rp u1</code> Open the repeater with the unmangled version of request 1</li>
<li><code>vfs u1</code> Throws an error because the unmangled version was never submitted</li>
<li><code>vfs s1</code> Throws an error because the response for request 1 was never mangled</li>
<li><code>vfs 2</code> Prints the mangled response of request 2</li>
<li><code>vfs s2</code> Prints the unmangled response of request 2</li>
<li><code>vfq u2</code> Throws an error because request 2's request was never mangled</li>
<li><code>vfs u2</code> Throws an error because request 2's request was never mangled</li>
</ul>

<h3><a id="user-content-passing-multiple-request-ids-to-a-command" class="anchor" href="#passing-multiple-request-ids-to-a-command" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Passing Multiple Request IDs to a Command</h3>

<p>Some arguments can take multiple IDs for an argument. To pass multiple IDs to a command, separate the IDs with commas <strong>(no spaces!)</strong>. A few examples:</p>

<ul>
<li><code>viq 1,2,u3</code> View information about requests 1, 2, and the unmangled version of 3</li>
<li><code>gma foo 4,5,6</code> Generate a macro with definitions for requests 4, 5, and 6</li>
</ul>

<h2><a id="user-content-context" class="anchor" href="#context" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Context</h2>

<p>The context is a set of filters that define which requests are considered "active". Only requests in the current context are displayed with <code>ls</code>. By default, the context includes every single request that passes through the proxy. You can limit down the current context by applying filters. Filters apply rules such as "the response code must equal 500" or "the host must contain google.com". Once you apply one or more filters, only requests/responses which pass every active filter will be a part of the current context.</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>f &lt;filter string&gt;</code></td>
<td align="left">filter, fl, f</td>
<td align="left">Add a filter that limits which requests are included in the current context. See the Filter String section for how to create a filter string</td>
</tr>
<tr>
<td align="left"><code>fc</code></td>
<td align="left">filter_clear, fc</td>
<td align="left">Clears the filters and resets the context to contain all requests and responses. Ignores scope</td>
</tr>
<tr>
<td align="left"><code>fu</code></td>
<td align="left">filter_up, fu</td>
<td align="left">Removes the most recently applied filter</td>
</tr>
<tr>
<td align="left"><code>fls</code></td>
<td align="left">filter_list, fls</td>
<td align="left">Print the filters that make up the current context</td>
</tr>
<tr>
<td align="left"><code>filter_prune</code></td>
<td align="left">filter_prune</td>
<td align="left">Delete all the requests that aren't in the current context from the data file</td>
</tr>
</tbody></table>

<h2><a id="user-content-filter-strings" class="anchor" href="#filter-strings" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Filter Strings</h2>

<p>Filter strings define a condition that a request/response pair must pass to be part of the context. Most filter strings have the following format:</p>

<pre><code>&lt;field&gt; &lt;comparer&gt; &lt;value&gt;
</code></pre>

<p>Where <code>&lt;field&gt;</code> is some part of the request/response, <code>&lt;comparer&gt;</code> is some comparison to <code>&lt;value&gt;</code>. For example, if you wanted a filter that only matches requests to <code>target.org</code>, you could use the following filter string:</p>

<pre><code>host is target.org

field = "host"
comparer = "is"
value = "target.org"
</code></pre>

<p>Also <strong>if you prefix a comparer with 'n' it turns it into a negation.</strong> Using the previous example, the following will match any request except for ones where the host contains <code>target.org</code>:</p>

<pre><code>host nis target.org

field = "host"
comparer = "nis"
value = "target.org"
</code></pre>

<p>For fields that are a list of key/value pairs (headers, get params, post params, and cookies) you can use the following format:</p>

<pre><code>&lt;field&gt; &lt;comparer1&gt; &lt;value1&gt;[ &lt;comparer2&gt; &lt;value2&gt;]
</code></pre>

<p>This is a little more complicated. If you don't give comparer2/value2, the filter will pass any pair where the key or the value matches comparer1 and value1. If you do give comparer2/value2, the key must match comparer1/value1 and the value must match comparer2/value2 For example:</p>

<pre><code>Filter A:
    cookie contains Session

Filter B:
    cookie contains Session contains 456

Filter C:
    cookie ncontains Ultra

Cookie: SuperSession=abc123
Matches A and C but not B

Cookie: UltraSession=abc123456
Matches both A and B but not C
</code></pre>

<h3><a id="user-content-list-of-fields" class="anchor" href="#list-of-fields" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>List of fields</h3>

<table><thead>
<tr>
<th align="left">Field Name</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
<th align="left">Format</th>
</tr>
</thead><tbody>
<tr>
<td align="left">all</td>
<td align="left">all</td>
<td align="left">The entire request represented as one string</td>
<td align="left">String</td>
</tr>
<tr>
<td align="left">host</td>
<td align="left">host, domain, hs, dm</td>
<td align="left">The target host (ie <a href="http://www.target.com">www.target.com</a>)</td>
<td align="left">String</td>
</tr>
<tr>
<td align="left">path</td>
<td align="left">path, pt</td>
<td align="left">The path of the url (ie /path/to/secrets.php)</td>
<td align="left">String</td>
</tr>
<tr>
<td align="left">body</td>
<td align="left">body, data, bd, dt</td>
<td align="left">The body (data section) of either the request or the response</td>
<td align="left">String</td>
</tr>
<tr>
<td align="left">reqbody</td>
<td align="left">qbody, qdata, qbd, qdt</td>
<td align="left">The body (data section) of th request</td>
<td align="left">String</td>
</tr>
<tr>
<td align="left">rspbody</td>
<td align="left">sbody, sdata, sbd, sdt</td>
<td align="left">The body (data section) of th response</td>
<td align="left">String</td>
</tr>
<tr>
<td align="left">verb</td>
<td align="left">verb, vb</td>
<td align="left">The HTTP verb of the request (ie GET, POST)</td>
<td align="left">String</td>
</tr>
<tr>
<td align="left">param</td>
<td align="left">param, pm</td>
<td align="left">Either the get or post parameters</td>
<td align="left">Key/Value</td>
</tr>
<tr>
<td align="left">header</td>
<td align="left">header, hd</td>
<td align="left">An HTTP header (ie User-Agent, Basic-Authorization) in the request or response</td>
<td align="left">Key/Value</td>
</tr>
<tr>
<td align="left">reqheader</td>
<td align="left">reqheader, qhd</td>
<td align="left">An HTTP header in the request</td>
<td align="left">Key/Value</td>
</tr>
<tr>
<td align="left">rspheader</td>
<td align="left">rspheader, shd</td>
<td align="left">An HTTP header in the response</td>
<td align="left">Key/Value</td>
</tr>
<tr>
<td align="left">rawheaders</td>
<td align="left">rawheaders, rh</td>
<td align="left">The entire header section (as one string) of either the head or the response</td>
<td align="left">String</td>
</tr>
<tr>
<td align="left">sentcookie</td>
<td align="left">sentcookie, sck</td>
<td align="left">A cookie sent in a request</td>
<td align="left">Key/Value</td>
</tr>
<tr>
<td align="left">setcookie</td>
<td align="left">setcookie, stck</td>
<td align="left">A cookie set by a response</td>
<td align="left">Key/Value</td>
</tr>
<tr>
<td align="left">statuscode</td>
<td align="left">statuscode, sc, responsecode</td>
<td align="left">The response code of the response</td>
<td align="left">Numeric</td>
</tr>
<tr>
<td align="left">tag</td>
<td align="left">tag</td>
<td align="left">Any of the tags applied to the request</td>
<td align="left">String</td>
</tr>
</tbody></table>

<h3><a id="user-content-list-of-comparers" class="anchor" href="#list-of-comparers" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>List of comparers</h3>

<table><thead>
<tr>
<th align="left">Field Name</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left">is</td>
<td align="left">is</td>
<td align="left">Exact string match</td>
</tr>
<tr>
<td align="left">contains</td>
<td align="left">contains, ct</td>
<td align="left">A contain B is true if B is a substring of A</td>
</tr>
<tr>
<td align="left">containsr</td>
<td align="left">containsr, ctr</td>
<td align="left">A containr B is true if A matches regexp B</td>
</tr>
<tr>
<td align="left">exists</td>
<td align="left">exists, ex</td>
<td align="left">A exists B if A is not an empty string (likely buggy)</td>
</tr>
<tr>
<td align="left">Leq</td>
<td align="left">Leq</td>
<td align="left">A Leq B if A's length equals B (B must be a number)</td>
</tr>
<tr>
<td align="left">Lgt</td>
<td align="left">Lgt</td>
<td align="left">A Lgt B if A's length is greater than B (B must be a number )</td>
</tr>
<tr>
<td align="left">Llt</td>
<td align="left">Llt</td>
<td align="left">A Llt B if A's length is less than B (B must be a number)</td>
</tr>
<tr>
<td align="left">eq</td>
<td align="left">eq</td>
<td align="left">A eq B if A = B (A and B must be a number)</td>
</tr>
<tr>
<td align="left">gt</td>
<td align="left">gt</td>
<td align="left">A gt B if A &gt; B (A and B must be a number)</td>
</tr>
<tr>
<td align="left">lt</td>
<td align="left">lt</td>
<td align="left">A lt B if A &lt; B (A and B must be a number)</td>
</tr>
</tbody></table>

<h3><a id="user-content-special-form-filters" class="anchor" href="#special-form-filters" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Special form filters</h3>

<p>A few filters don't conform to the field, comparer, value format. You can still negate these.</p>

<table><thead>
<tr>
<th align="left">Format</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left">before </td>
<td align="left">before, bf, b4</td>
<td align="left">Filters out any request that is not before the given request. Filters out any request without a time.</td>
</tr>
<tr>
<td align="left">after </td>
<td align="left">after, af</td>
<td align="left">Filters out any request that is not before the given request. Filters out any request without a time.</td>
</tr>
<tr>
<td align="left">inv </td>
<td align="left">inf</td>
<td align="left">Inverts a filter string. Anything that matches the filter string will not pass the filter.</td>
</tr>
</tbody></table>

<p>Examples:</p>

<pre><code>Only show requests before request 1234
  f b4 1234

Only show requests after request 1234
  f af 1234

Show requests without a csrf parameter
  f inv param ct csrf
</code></pre>

<h2><a id="user-content-scope" class="anchor" href="#scope" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Scope</h2>

<p>Scope is a set of rules to define whether Pappy should mess with a request. You define the scope by setting the context to what you want the scope to be and running <code>scope_save</code>. The scope is saved in the data file and is automatically restored when using the same project directory.</p>

<p>Any requests which don't match all the filters in the scope will be passed straight to the browser and will not be caught by the interceptor or recorded in the data file. This is useful to make sure you don't accidentally do something like log in to your email through the proxy and have your plaintext username/password stored.</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>scope_save</code></td>
<td align="left"><code>scope_save</code></td>
<td align="left">Set the current context to be the scope</td>
</tr>
<tr>
<td align="left"><code>sr</code></td>
<td align="left"><code>scope_reset</code>, <code>sr</code></td>
<td align="left">Set the current context to the scope</td>
</tr>
<tr>
<td align="left"><code>scope_delete</code></td>
<td align="left"><code>scope_delete</code></td>
<td align="left">Clear the scope (everything's in scope!)</td>
</tr>
<tr>
<td align="left"><code>scope_list</code></td>
<td align="left"><code>scope_list</code>, <code>sls</code></td>
<td align="left">List all the filters that are applied to the scope</td>
</tr>
</tbody></table>

<h3><a id="user-content-built-in-filters" class="anchor" href="#built-in-filters" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Built-In Filters</h3>

<p>Pappy also includes some built in filters that you can apply. These are things that you may want to filter by but may be too tedius to type out. The <code>fbi</code> command also supports tab completion.</p>

<table><thead>
<tr>
<th align="left">Filter</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>not_image</code></td>
<td align="left">Matches anything that isn't an image.</td>
</tr>
<tr>
<td align="left"><code>not_jscss</code></td>
<td align="left">Matches anything that isn't JavaScript or CSS.</td>
</tr>
</tbody></table>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>fbi &lt;filter&gt;</code></td>
<td align="left"><code>builtin_filter</code>, <code>fbi</code></td>
<td align="left">Apply a built-in filter to the current context</td>
</tr>
</tbody></table>

<h2><a id="user-content-decoding-strings" class="anchor" href="#decoding-strings" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Decoding Strings</h2>

<p>These features try to fill a similar role to Burp's decoder. Each command will automatically copy the results to the clipboard. In addition, if no string is given, the commands will encode/decode whatever is already in the clipboard. Here is an example of how to base64 encode/decode a string.</p>

<pre><code>pappy&gt; b64e "Hello World!"
SGVsbG8gV29ybGQh
pappy&gt; b64d
Hello World!
pappy&gt;
</code></pre>

<p>And if the result contains non-printable characters, a hexdump will be produced instead</p>

<pre><code>pappy&gt; b64d ImALittleTeapot=
0000  22 60 0b 8a db 65 79 37 9a a6 8b                  "`...ey7...

pappy&gt;
</code></pre>

<p>The following commands can be used to encode/decode strings:</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>base64_decode</code></td>
<td align="left"><code>base64_decode</code>, <code>b64d</code></td>
<td align="left">Base64 decode a string</td>
</tr>
<tr>
<td align="left"><code>base64_encode</code></td>
<td align="left"><code>base64_encode</code>, <code>b64e</code></td>
<td align="left">Base64 encode a string</td>
</tr>
<tr>
<td align="left"><code>asciihex_decode</code></td>
<td align="left"><code>asciihex_decode</code>, <code>ahd</code></td>
<td align="left">Decode an ASCII hex string</td>
</tr>
<tr>
<td align="left"><code>asciihex_encode</code></td>
<td align="left"><code>asciihex_encode</code>, <code>ahe</code></td>
<td align="left">Encode an ASCII hex string</td>
</tr>
<tr>
<td align="left"><code>html_decode</code></td>
<td align="left"><code>html_decode</code>, <code>htmld</code></td>
<td align="left">Decode an html encoded string</td>
</tr>
<tr>
<td align="left"><code>html_encode</code></td>
<td align="left"><code>html_encode</code>, <code>htmle</code></td>
<td align="left">Encode a string to html encode all of the characters</td>
</tr>
<tr>
<td align="left"><code>url_decode</code></td>
<td align="left"><code>url_decode</code>, <code>urld</code></td>
<td align="left">Url decode a string</td>
</tr>
<tr>
<td align="left"><code>url_encode</code></td>
<td align="left"><code>url_encode</code>, <code>urle</code></td>
<td align="left">Url encode a string</td>
</tr>
<tr>
<td align="left"><code>gzip_decode</code></td>
<td align="left"><code>gzip_decode</code>, <code>gzd</code></td>
<td align="left">Gzip decompress a string. Probably won't work too well since there's not a great way to get binary data passed in as an argument. I'm working on this.</td>
</tr>
<tr>
<td align="left"><code>gzip_encode</code></td>
<td align="left"><code>gzip_encode</code>, <code>gze</code></td>
<td align="left">Gzip compress a string. Result doesn't get copied to the clipboard.</td>
</tr>
<tr>
<td align="left"><code>base64_decode_raw</code></td>
<td align="left"><code>base64_decode_raw</code>, <code>b64dr</code></td>
<td align="left">Same as <code>base64_decode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>base64_encode_raw</code></td>
<td align="left"><code>base64_encode_raw</code>, <code>b64er</code></td>
<td align="left">Same as <code>base64_encode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>asciihex_decode_raw</code></td>
<td align="left"><code>asciihex_decode_raw</code>, <code>ahdr</code></td>
<td align="left">Same as <code>asciihex_decode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>asciihex_encode_raw</code></td>
<td align="left"><code>asciihex_encode_raw</code>, <code>aher</code></td>
<td align="left">Same as <code>asciihex_encode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>html_decode_raw</code></td>
<td align="left"><code>html_decode_raw</code>, <code>htmldr</code></td>
<td align="left">Same as <code>html_decode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>html_encode_raw</code></td>
<td align="left"><code>html_encode_raw</code>, <code>htmler</code></td>
<td align="left">Same as <code>html_encode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>url_decode_raw</code></td>
<td align="left"><code>url_decode_raw</code>, <code>urldr</code></td>
<td align="left">Same as <code>url_decode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>url_encode_raw</code></td>
<td align="left"><code>url_encode_raw</code>, <code>urler</code></td>
<td align="left">Same as <code>url_encode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>gzip_decode_raw</code></td>
<td align="left"><code>gzip_decode_raw</code>, <code>gzdr</code></td>
<td align="left">Same as <code>gzip_decode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>gzip_encode_raw</code></td>
<td align="left"><code>gzip_encode_raw</code>, <code>gzer</code></td>
<td align="left">Same as <code>gzip_encode</code> but will not print a hexdump if it contains non-printable characters. It is suggested you use <code>&gt;</code> to redirect the output to a file.</td>
</tr>
<tr>
<td align="left"><code>unixtime_decode</code></td>
<td align="left"><code>unixtime_decode</code>, <code>uxtd</code></td>
<td align="left">Take in a unix timestamp and print a human readable timestamp</td>
</tr>
</tbody></table>

<h2><a id="user-content-interceptor" class="anchor" href="#interceptor" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Interceptor</h2>

<p>This feature is like Burp's proxy with "Intercept Mode" turned on, except it's not turned on unless you explicitly turn it on. When the proxy gets a request while in intercept mode, it lets you edit it before forwarding it to the server. In addition, it can stop responses from the server and let you edit them before they get forwarded to the browser. When you run the command, you can pass <code>req</code> and/or <code>rsp</code> as arguments to say whether you would like to intercept requests and/or responses. Only in-scope requests/responses will be intercepted (see Scope section).</p>

<p>The interceptor will use your EDITOR variable to decide which editor to edit the request/response with. If no editor variable is set, it will default to <code>vi</code>.</p>

<p>To forward a request, edit it, save the file, then quit.</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>ic &lt;req,rsp&gt;+</code></td>
<td align="left"><code>intercept</code>, <code>ic</code></td>
<td align="left">Begins interception mode. Press enter to leave interception mode and return to the command prompt. Pass in <code>request</code> to intercept requests, <code>response</code> to intercept responses, or both to intercept both.</td>
</tr>
</tbody></table>

<pre><code>Intercept both requests and responses:
&gt; ic requests responses
&gt; ic req rsp

Intercept just requests:
&gt; ic requests
&gt; ic req

Intercept just responses:
&gt; ic responses
&gt; ic rsp

Be totally useless:
&gt; ic
</code></pre>

<p>To drop a request, delete everything, save and quit.</p>

<h2><a id="user-content-repeater" class="anchor" href="#repeater" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Repeater</h2>

<p>This feature is like Burp's repeater (yes, really). You choose a request and Pappy will open vim in a split window with your request on the left and the original response on the right. You can make changes to the request and then run ":RepeaterSubmitBuffer" to submit the modified request. The response will be displayed on the right. This command is bound to <code>&lt;leader&gt;f</code> by default, but you can bind it to something else too in your vimrc (I think, dunno if vim will complain if the function undefined which it will be for regular files). This command will submit whatever buffer your cursor is in, so make sure it's in the request buffer.</p>

<p>When you're done with repeater, run ":qa!" to avoid having to save changes to nonexistent files.</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>rp &lt;id&gt;</code></td>
<td align="left">repeater, rp</td>
<td align="left">Open the specified request in the repeater</td>
</tr>
</tbody></table>

<table><thead>
<tr>
<th align="left">Vim Command</th>
<th align="left">Keybinding</th>
<th align="left">Action</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>RepeaterSubmitBuffer</code></td>
<td align="left">f</td>
<td align="left">Submit the current buffer, split the windows vertically, and show the result in the right window</td>
</tr>
</tbody></table>

<h2><a id="user-content-macros" class="anchor" href="#macros" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Macros</h2>

<p>Macros are Pappy's version of Burp's intruder. You can use macros to make automated requests through the proxy and save them to the data file. A macro file is any python script file in the current directory that is in the form <code>macro_&lt;name&gt;.py</code>. An example project directory with macros would be:</p>

<pre><code>$ ls -l
-rw-r--r-- 1 scaryhacker wheel     150 Nov 26 11:17 config.json
-rw------- 1 scaryhacker wheel 2639872 Nov 26 17:18 data.db
-rw-r--r-- 1 scaryhacker wheel     471 Nov 26 18:42 macro_blank.py
-rw-r--r-- 1 scaryhacker wheel     264 Nov 26 18:49 macro_hackthensa.py
-rw-r--r-- 1 scaryhacker wheel    1261 Nov 26 18:37 macro_testgen.py
-rw-r--r-- 1 scaryhacker wheel     241 Nov 26 17:18 macro_test.py
</code></pre>

<p>In this case we have a <code>blank</code>, <code>hackthensa</code>, <code>testgen</code>, and <code>test</code> macro. A macro script is any python script that defines a <code>run_macro(args)</code> function and a <code>MACRO_NAME</code> variable. For example, a simple macro would be:</p>

<pre><code>### macro_print.py

MACRO_NAME = 'Print Macro'

def run_macro(args):
    if args:
        print "Hello, %s!" % args[0]
    else:
        print "Hello, Pappy!"
</code></pre>

<p>You can place this macro in your project directory then load and run it from Pappy. When a macro is run, arguments are passed from the command line. Arguments are separated the same way as they are on the command line, so if you want to use spaces in your argument, you have to put quotes around it.</p>

<pre><code>$ pappy
Proxy is listening on port 8000
pappy&gt; lma
Loaded "&lt;Macro Test Macro (tm/test)&gt;"
Loaded "&lt;Macro Macro 6494496 (testgen)&gt;"
Loaded "&lt;Macro Print Macro (print)&gt;"
Loaded "&lt;Macro Hack the NSA (htnsa/hackthensa)&gt;"
Loaded "&lt;Macro Macro 62449408 (blank)&gt;"
pappy&gt; rma print
Hello, Pappy!
pappy&gt; rma print NSA
Hello, NSA!
pappy&gt; rma print Idiot Slayer
Hello, Idiot!
pappy&gt; rma print "Idiot Slayer"
Hello, Idiot Slayer!
</code></pre>

<p>You'll need to run <code>lma</code> every time you make a change to the macro in order to reload it. In addition, any code outside of the <code>run_macro</code> function will be run when it the macro gets loaded.</p>

<h3><a id="user-content-generating-macros-from-requests" class="anchor" href="#generating-macros-from-requests" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Generating Macros From Requests</h3>

<p>You can also generate macros that have Pappy <code>Request</code> objects created with the same information as requests you've already made. For example:</p>

<pre><code>$ pappy
Proxy is listening on port 8000
pappy&gt; ls
ID  Verb  Host         Path               S-Code  Req Len  Rsp Len  Time  Mngl
5   GET   vitaly.sexy  /esr1.jpg          200 OK  0        17653    --    --
4   GET   vitaly.sexy  /netscape.gif      200 OK  0        1135     --    --
3   GET   vitaly.sexy  /construction.gif  200 OK  0        28366    --    --
2   GET   vitaly.sexy  /vitaly2.jpg       200 OK  0        2034003  --    --
1   GET   vitaly.sexy  /                  200 OK  0        1201     --    --
pappy&gt; gma sexy 1
Wrote script to macro_sexy.py
pappy&gt; quit
$ cat macro_sexy.py
from pappyproxy.http import Request, get_request, post_request

MACRO_NAME = 'Macro 94664581'
SHORT_NAME = ''

###########
## Requests

req0 = Request((
'GET / HTTP/1.1\r\n'
'Host: vitaly.sexy\r\n'
'User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0\r\n'
'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n'
'Accept-Language: en-US,en;q=0.5\r\n'
'Accept-Encoding: gzip, deflate\r\n'
'Connection: keep-alive\r\n'
'Pragma: no-cache\r\n'
'Cache-Control: no-cache\r\n'
'\r\n'
))


def run_macro(args):
    # Example:
    # req = req0.copy() # Copy req0
    # req.submit() # Submit the request to get a response
    # print req.response.raw_headers # print the response headers
    # req.save() # save the request to the data file
    # or copy req0 into a loop and use string substitution to automate requests
    pass
</code></pre>

<p>If you enter in a value for <code>SHORT_NAME</code>, you can use it as a shortcut to run that macro. So if in a macro you set <code>SHORT_NAME='tm'</code> you can run it by running <code>pappy&gt; rma tm</code>.</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>lma [dir]</code></td>
<td align="left"><code>load_macros</code>, <code>lma</code></td>
<td align="left">Load macros from a directory. If <code>dir</code> is not given, use the current directory (the project directory)</td>
</tr>
<tr>
<td align="left"><code>rma &lt;macro name&gt;</code></td>
<td align="left"><code>run_macro</code>, <code>rma</code></td>
<td align="left">Run a macro with the given name. You can use the shortname, filename, or long name.</td>
</tr>
<tr>
<td align="left"><code>gma &lt;name&gt; [id(s)]</code></td>
<td align="left"><code>generate_macro</code>, <code>gma</code></td>
<td align="left">Generate a macro with the given name. If request IDs are given, the macro will contain request objects that contain each request.</td>
</tr>
<tr>
<td align="left"><code>rpy &lt;id(s)&gt;</code></td>
<td align="left"><code>rpy</code></td>
<td align="left">Print the Python object definitions for each of the given ids</td>
</tr>
</tbody></table>

<h3><a id="user-content-request-objects" class="anchor" href="#request-objects" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Request Objects</h3>

<p>The main method of interacting with the proxy is through <code>Request</code> objects. You can submit a request with <code>req.sumbit()</code> and save it to the data file with <code>req.save()</code>. The objects also have attributes which can be used to modify the request in a high-level way. You can see the <a href="https://roglew.github.io/pappy-proxy/pappyproxy.html#module-pappyproxy.http">full documentation</a> for more details on using these objects.</p>

<p>Dict-like objects are represented with a custom class called a <code>RepeatableDict</code>. Again, look at the docs for details. For the most part, you can interact with it like a normal dictionary, but don't be surprised if it's missing some methods you would expect.</p>

<p>Here is a quick list of attributes that you can use with <code>Request</code> objects:</p>

<table><thead>
<tr>
<th align="left">Attribute</th>
<th align="left">Settable?</th>
<th align="left">Data Type</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left">cookies</td>
<td align="left">Yes</td>
<td align="left">RepeatableDict</td>
<td align="left">Cookies sent in the request</td>
</tr>
<tr>
<td align="left">fragment</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The url fragment (The text after the #)</td>
</tr>
<tr>
<td align="left">full_path</td>
<td align="left">No</td>
<td align="left">String</td>
<td align="left">The path including url params and the fragment</td>
</tr>
<tr>
<td align="left">full_request</td>
<td align="left">No</td>
<td align="left">String</td>
<td align="left">The full request including headers and data</td>
</tr>
<tr>
<td align="left">headers</td>
<td align="left">Yes</td>
<td align="left">RepeatableDict</td>
<td align="left">The headers of the request</td>
</tr>
<tr>
<td align="left">host</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The host that the request is sent to</td>
</tr>
<tr>
<td align="left">is_ssl</td>
<td align="left">Yes</td>
<td align="left">Bool</td>
<td align="left">Whether the request is/was sent over SSL</td>
</tr>
<tr>
<td align="left">path</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The document path (ie <a href="http://www.a.com/this/is/the/path">www.a.com/this/is/the/path</a>)</td>
</tr>
<tr>
<td align="left">port</td>
<td align="left">Yes</td>
<td align="left">Integer</td>
<td align="left">The port the request is/was sent to</td>
</tr>
<tr>
<td align="left">post_params</td>
<td align="left">Yes</td>
<td align="left">RepeatableDict</td>
<td align="left">Post parameters</td>
</tr>
<tr>
<td align="left">raw_data</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The data part of the request</td>
</tr>
<tr>
<td align="left">raw_headers</td>
<td align="left">No</td>
<td align="left">String</td>
<td align="left">The text of the headers section of the request</td>
</tr>
<tr>
<td align="left">reqid</td>
<td align="left">Yes</td>
<td align="left">Integer</td>
<td align="left">The ID of the request. If set when save() is called, it replaces the request with the same id in the database</td>
</tr>
<tr>
<td align="left">response</td>
<td align="left">Yes</td>
<td align="left">Response</td>
<td align="left">The associated response for the request</td>
</tr>
<tr>
<td align="left">rsptime</td>
<td align="left">No</td>
<td align="left">Datetime Delta</td>
<td align="left">The time it took to complete the request. Set when submit() is called</td>
</tr>
<tr>
<td align="left">status_line</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The status line of the request (ie 'GET / HTTP/1.1')</td>
</tr>
<tr>
<td align="left">time_end</td>
<td align="left">Yes</td>
<td align="left">Datetime</td>
<td align="left">The time when the request was completed</td>
</tr>
<tr>
<td align="left">time_start</td>
<td align="left">Yes</td>
<td align="left">Datetime</td>
<td align="left">The time when the request was started</td>
</tr>
<tr>
<td align="left">unmangled</td>
<td align="left">Yes</td>
<td align="left">Request</td>
<td align="left">If the request was mangled, the unmangled version of the request</td>
</tr>
<tr>
<td align="left">url</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The URL of the request (ie '<a href="https://www.google.com">https://www.google.com</a>')</td>
</tr>
<tr>
<td align="left">url_params</td>
<td align="left">Yes</td>
<td align="left">RepeatableDict</td>
<td align="left">The URL parameters of the request</td>
</tr>
<tr>
<td align="left">verb</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The verb used for the request (ie GET, POST, PATCH, HEAD, etc). Doesn't have to be a valid verb.</td>
</tr>
<tr>
<td align="left">version</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The version part of the status line (ie 'HTTP/1.1')</td>
</tr>
</tbody></table>

<p>Request methods:</p>

<table><thead>
<tr>
<th align="left">Function</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left">submit()</td>
<td align="left">Submit the request through the proxy. Does not save the request to the data file</td>
</tr>
<tr>
<td align="left">save()</td>
<td align="left">Save the request, its unmangled version, its associated response, and the unmangled version of the response to the database</td>
</tr>
</tbody></table>

<p>And here is a quick list of attributes that you can use with <code>Response</code> objects:</p>

<table><thead>
<tr>
<th align="left">Attribute</th>
<th align="left">Settable?</th>
<th align="left">Data Type</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left">cookies</td>
<td align="left">Yes</td>
<td align="left">RepeatableDict</td>
<td align="left">Cookies set by the response</td>
</tr>
<tr>
<td align="left">headers</td>
<td align="left">Yes</td>
<td align="left">RepeatableDict</td>
<td align="left">The headers of the response</td>
</tr>
<tr>
<td align="left">response_code</td>
<td align="left">Yes</td>
<td align="left">Integer</td>
<td align="left">The response code of the response</td>
</tr>
<tr>
<td align="left">response_text</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The text associated with the response code (ie OK, NOT FOUND)</td>
</tr>
<tr>
<td align="left">rspid</td>
<td align="left">Yes</td>
<td align="left">Integer</td>
<td align="left">The response id of the response. If this is the same as another response in the database, calling save() on the associated request will replace that response in the database</td>
</tr>
<tr>
<td align="left">unmangled</td>
<td align="left">Yes</td>
<td align="left">Response</td>
<td align="left">If the response was mangled, this will refer to the unmangled version of the response. Otherwise it is None</td>
</tr>
<tr>
<td align="left">version</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The version part of the status line of the response (ie 'HTTP/1.1')</td>
</tr>
<tr>
<td align="left">raw_headers</td>
<td align="left">No</td>
<td align="left">String</td>
<td align="left">A text version of the headers of the response</td>
</tr>
<tr>
<td align="left">status_line</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The status line of the response</td>
</tr>
<tr>
<td align="left">raw_data</td>
<td align="left">Yes</td>
<td align="left">String</td>
<td align="left">The data portion of the response</td>
</tr>
<tr>
<td align="left">full_response</td>
<td align="left">No</td>
<td align="left">String</td>
<td align="left">The full text version of the response including headers and data</td>
</tr>
</tbody></table>

<p>Like I said, these interfaces are prone to change and will probably crash when you use them. If you get a traceback, send me an email so I can fix it.</p>

<h3><a id="user-content-useful-functions" class="anchor" href="#useful-functions" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Useful Functions</h3>

<p>There are also a few functions which could be useful for creating requests in macros. It's worth pointing out that <code>request_by_id</code> is useful for passing request objects as arguments. For example, here is a macro that lets you resubmit a request with the Google Bot user agent:</p>

<pre><code>## macro_googlebot.py

from pappyproxy.http import Request, get_request, post_request, request_by_id
from pappyproxy.context import set_tag
from pappyproxy.iter import *

MACRO_NAME = 'Submit as Google'
SHORT_NAME = ''

def run_macro(args):
    req = request_by_id(args[0])
    req.headers['User-Agent'] = "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
    req.submit()
    req.save()
</code></pre>

<table><thead>
<tr>
<th align="left">Function</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left">get_request(url, url_params={})</td>
<td align="left">Returns a Request object that contains a GET request to the given url with the given url params</td>
</tr>
<tr>
<td align="left">post_request(url, post_params={}, url_params={})</td>
<td align="left">Returns a Request object that contains a POST request to the given url with the given url and post params</td>
</tr>
<tr>
<td align="left">request_by_id(reqid)</td>
<td align="left">Get a request object from its id.</td>
</tr>
</tbody></table>

<h2><a id="user-content-intercepting-macros" class="anchor" href="#intercepting-macros" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Intercepting Macros</h2>

<p>Intercepting macros let you mangle requests as they pass through the proxy. Similarly to normal macros, an intercepting macro is any python script with an "int" prefix. For example, <code>int_name.py</code> would be a valid intercepting macro name. They are also loaded with the <code>lma</code> command. An intercepting macro can define two functions: <code>mangle_request</code> or <code>mangle_response</code>. Both requests only take a <code>Request</code> object as a parameter. <code>mangle_request</code> returns either a new, modified Request object to change it, or it can return the original object to not mangle it. The <code>mange_response</code> must return a <code>Response</code> (not request!) object. The request passed in to <code>mangle_response</code> will have an associated response with it. If you want to modify the response, copy <code>request.response</code>, make modifications, then return it. If you would like to pass it through untouched, just return <code>request.response</code>.</p>

<p>Note, that due to twisted funkyness, <em>you cannot save requests from intercepting macros</em>. Technically you <strong>can</strong>, but to do that you'll have to define <code>async_mangle_request</code> (or response) instead of <code>mangle_request</code> (or response) then use <code>Request.async_deep_save</code> which generates a deferred, then generate a deferred from <code>async_mangle_requests</code> (inline callbacks work too). If you've never used twisted before, please don't try. Twisted is hard. Plus the mangled request will be saved before it is submitted anyways.</p>

<p>Confusing? Here are some example intercepting macros:</p>

<pre><code>## int_cloud2butt.py

import string

MACRO_NAME = 'Cloud to Butt'

def mangle_response(request):
    r = request.response.copy()
    r.raw_data = string.replace(r.raw_data, 'cloud', 'butt')
    r.raw_data = string.replace(r.raw_data, 'Cloud', 'Butt')
    return r
</code></pre>

<pre><code>## int_donothing.py

import string

MACRO_NAME = 'Do Nothing'

def mangle_request(request):
    return request

def mangle_response(request):
    return request.response
</code></pre>

<pre><code>## int_adminplz.py

from base64 import base64encode as b64e

MACRO_NAME = 'Admin Session'

def mangle_request(request):
    r = request.copy()
    r.headers['Authorization'] = 'Basic %s' % b64e('Admin:Password123')
    return r
</code></pre>

<p>In addition, you can use an <code>init(args)</code> function to get arguments from the command line. If no arguments are passed, args will be an empty list. Here is an example macro that does a search and replace:</p>

<pre><code>## int_replace.py

MACRO_NAME = 'Find and Replace'
SHORT_NAME = ''
runargs = []

def init(args):
    global runargs
    runargs = args

def mangle_request(request):
    global runargs
    if len(runargs) &lt; 2:
        return request
    request.body = request.body.replace(runargs[0], runargs[1])
    return request

def mangle_response(request):
    global runargs
    if len(runargs) &lt; 2:
        return request.response
    request.response.body = request.response.body.replace(runargs[0], runargs[1])
    return request.response
</code></pre>

<p>You can use this macro to do any search and replace that you want. For example, if you wanted to replace "Google" with "Skynet", you can run the macro like this:</p>

<pre><code>pappy&gt; lma
Loaded "&lt;InterceptingMacro Find and Replace (replace)&gt;"
pappy&gt; rim replace Google Skynet
"Find and Replace" started
pappy&gt; 
</code></pre>

<p>Now every site that you visit will be a little bit more accurate.</p>

<h3><a id="user-content-enablingdisabling-intercepting-macros" class="anchor" href="#enablingdisabling-intercepting-macros" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Enabling/Disabling Intercepting Macros</h3>

<p>You can use the following commands to start/stop intercepting macros</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>lma [dir]</code></td>
<td align="left"><code>load_macros</code>, <code>lma</code></td>
<td align="left">Load macros from a directory. If <code>dir</code> is not given, use the current directory (the project directory)</td>
</tr>
<tr>
<td align="left"><code>rim &lt;macro name&gt;</code></td>
<td align="left"><code>run_int_macro</code>, <code>rim</code></td>
<td align="left">Run an intercepting macro. Similarly to normal macros you can use the name, short name, or file name of the macro.</td>
</tr>
<tr>
<td align="left"><code>sim &lt;macro name&gt; [args]</code></td>
<td align="left"><code>stop_int_macro</code>, <code>sim</code></td>
<td align="left">Stop an intercepting macro. If arguments are given, they will be passed to the macro's <code>init(args)</code> function if it exists.</td>
</tr>
<tr>
<td align="left"><code>lim</code></td>
<td align="left"><code>list_int_macros</code>, <code>lsim</code></td>
<td align="left">List all enabled/disabled intercepting macros</td>
</tr>
<tr>
<td align="left"><code>gima &lt;name&gt;</code></td>
<td align="left"><code>generate_int_macro</code>, <code>gima</code></td>
<td align="left">Generate an intercepting macro with the given name.</td>
</tr>
</tbody></table>

<h2><a id="user-content-logging" class="anchor" href="#logging" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Logging</h2>

<p>You can watch in real-time what requests are going through the proxy. Verbosisty defaults to 1 which just states when connections are made/lost and some information on what is happening. If verbosity is set to 3, it includes all the data which is sent through the proxy and processed. It will print the raw response from the server, what it decodes it to, etc. Even if you don't run this command, all the information is stored in the dubug directory (the directory is cleared every start though!)</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>log [verbosity]</code></td>
<td align="left">View the log at the given verbosity. Default verbosity is 1 which just shows connections being made/lost and some other info, verbosity 3 shows full requests/responses as they pass through and are processed by the proxy</td>
</tr>
</tbody></table>

<h2><a id="user-content-additional-commands-and-features" class="anchor" href="#additional-commands-and-features" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Additional Commands and Features</h2>

<p>This is a list of other random stuff you can do that isn't categorized under anything else. These are mostly commands that I found that I needed while doing a test and just added. They likely don't do a ton of error checking.</p>

<table><thead>
<tr>
<th align="left">Command</th>
<th align="left">Aliases</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left"><code>dump_response &lt;reqid&gt; [filename]</code></td>
<td align="left"><code>dump_response</code></td>
<td align="left">Dumps the data from the response to the given filename (useful for images, .swf, etc). If no filename is given, it uses the name given in the path.</td>
</tr>
<tr>
<td align="left"><code>export &lt;req|rsp&gt; &lt;reqid&gt;</code></td>
<td align="left"><code>export</code></td>
<td align="left">Writes either the full request or response to a file in the current directory.</td>
</tr>
<tr>
<td align="left"><code>merge &lt;dbfile&gt;</code></td>
<td align="left"><code>merge</code></td>
<td align="left">Add all the requests from another datafile to the current datafile</td>
</tr>
</tbody></table>

<h3><a id="user-content-response-streaming" class="anchor" href="#response-streaming" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Response streaming</h3>

<p>If you don't have any intercepting macros running, Pappy will forward data to the browser as it gets it. However, if you're trying to mangle messages/responses, Pappy will need to download the entire message first.</p>

<h2><a id="user-content-plugins" class="anchor" href="#plugins" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Plugins</h2>

<p>Note that this section is a very quick overview of plugins. For a full description of how to write them, please see <a href="https://roglew.github.io/pappy-proxy/pappyplugins.html">the official docs</a>.</p>

<p>It is also possible to write plugins which are reusable across projects. Plugins are simply Python scripts located in <code>~/.pappy/plugins</code>. Plugins are able to create new console commands and maintain state throughout a Pappy session. They can access the same API as macros, but the plugin system is designed to allow you to create general purpose commands as compared to macros which are meant to be project-specific scripts. Still, it may not be a bad idea to try building a macro to do something in a quick and dirty way before writing a plugin since plugins are more complicated to write.</p>

<p>A simple hello world plugin could be something like:</p>

<pre><code>## hello.py
import shlex

def hello_world(line):
    if line:
        args = shlex.split(line)
        print 'Hello, %s!' % (', '.join(args))
    else:
        print "Hello, world!"

###############
## Plugin hooks

def load_cmds(cmd):
    cmd.set_cmds({
        'hello': (hello_world, None),
    })
    cmd.add_aliases([
        ('hello', 'hlo'),
        ('hello', 'ho'),
    ])
</code></pre>

<p>You can also create commands which support autocomplete:</p>

<pre><code>import shlex

_AUTOCOMPLETE_NAMES = ['alice', 'allie', 'sarah', 'mallory', 'slagathor']

def hello_world(line):
    if line:
        args = shlex.split(line)
        print 'Hello, %s!' % (', '.join(args))
    else:
        print "Hello, world!"

def complete_hello_world(text, line, begidx, endidx):
    return [n for n in _AUTOCOMPLETE_NAMES if n.startswith(text)]

###############
## Plugin hooks

def load_cmds(cmd):
    cmd.set_cmds({
        'hello': (hello_world, complete_hello_world),
    })
    cmd.add_aliases([
        ('hello', 'hlo'),
    ])
</code></pre>

<p>Then when you run Pappy you can use the <code>hello</code> command:</p>

<pre><code>$ pappy -l
Temporary datafile is /tmp/tmpBOXyJ3
Proxy is listening on port 8000
pappy&gt; ho
Hello, world!
pappy&gt; ho foo bar baz
Hello, foo, bar, baz!
pappy&gt; ho foo bar "baz lihtyur"
Hello, foo, bar, baz lihtyur!
pappy&gt;
</code></pre>

<h3><a id="user-content-should-i-write-a-plugin-or-a-macro" class="anchor" href="#should-i-write-a-plugin-or-a-macro" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Should I Write a Plugin or a Macro?</h3>

<p>A lot of the time, you can get away with writing a macro. However, you may consider writing a plugin if:</p>

<ul>
<li>You find yourself copying one macro to multiple projects</li>
<li>You want to write a general tool that can be applied to any website</li>
<li>You need to maintain state during the Pappy session</li>
</ul>

<p>My guess is that if you need one quick thing for a project, you're better off writing a macro first and seeing if you end up using it in future projects. Then if you find yourself needing it a lot, write a plugin for it. You may also consider keeping a <code>mine.py</code> plugin where you can write out commands that you use regularly but may not be worth creating a dedicated plugin for.</p>

<h2><a id="user-content-global-settings" class="anchor" href="#global-settings" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Global Settings</h2>

<p>There are some settings that apply to Pappy as a whole and are stored in <code>~/.pappy/global_config.json</code>. These settings are generally for tuning performance or modifying behavior on a system-wide level. No information about projects is put in here since it is world readable. You can technically add settings in here for plugins that you write, but if it's at all possible, please keep settings in the normal project config.</p>

<p>Settings included in <code>~/.pappy/global_config.json</code>:</p>

<table><thead>
<tr>
<th align="left">Setting</th>
<th align="left">Description</th>
</tr>
</thead><tbody>
<tr>
<td align="left">cache_size</td>
<td align="left">The number of requests from history that will be included in memory at any given time. Set to -1 to keep everything in memory. See the request cache section for more info.</td>
</tr>
</tbody></table>

<h2><a id="user-content-using-a-socks-server" class="anchor" href="#using-a-socks-server" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Using a SOCKS Server</h2>

<p>Pappy allows you to use an upstream SOCKS server. You can do this by adding a <code>socks_proxy</code> value to config.json. You can use the following for anonymous access to the proxy:</p>

<pre><code>    "socks_proxy": {"host":"socks.proxy.host", "port":5555}
</code></pre>

<p>To use credentials you add a <code>username</code> and <code>password</code> value to the dictionary:</p>

<pre><code>    "socks_proxy": {"host":"socks.proxy.host", "port":5555, "username": "mario", "password":"ilovemushrooms"}
</code></pre>

<p>Anything that passes through any of the active listeners will use the proxy.</p>

<h2><a id="user-content-transparent-host-redirection" class="anchor" href="#transparent-host-redirection" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Transparent Host Redirection</h2>

<p>Sometimes you get a frustrating thick client that doesn’t let you mess with proxy settings to get it to go through a proxy. However, if you can redirect where it sends its traffic to localhost, you can get Pappy to take that traffic and redirect it to go where it should.</p>

<p>It takes root permissions to listen on low numbered ports. As a result, we’ll need to do some root stuff to listen on ports 80 and 443 and get the data to Pappy. There are two ways to get the traffic to Pappy. The first is to set up port forwarding as root to send traffic from localhost:80 to localhost:8080 and localhost:443 to localhost:8443 (since we can listen on 8080 and 8443 without root). Or you can YOLO, run Pappy as root and just have it listen on 80 and 443.</p>

<p>According to Google you can use the following command to forward port 80 on localhost to 8080 on Linux:</p>

<pre><code>iptables -t nat -A PREROUTING -i ppp0 -p tcp --dport 80 -j REDIRECT --to-ports 8080
</code></pre>

<p>Then to route 443 to 8443:</p>

<pre><code>iptables -t nat -A PREROUTING -i ppp0 -p tcp --dport 443 -j REDIRECT --to-ports 8443
</code></pre>

<p>Of course, both of these need to be run as root.</p>

<p>Then on mac it’s</p>

<pre><code>echo "
rdr pass inet proto tcp from any to any port 80 -&gt; 127.0.0.1 port 8080
rdr pass inet proto tcp from any to any port 443 -&gt; 127.0.0.1 port 8443
" | sudo pfctl -ef -
Then to turn it off on mac it’s
sudo pfctl -F all -f /etc/pf.conf
</code></pre>

<p>Then modify the listener settings in the project’s config.json to be:</p>

<pre><code>"proxy_listeners": [
        {"port": 8080, "interface": "127.0.0.1", "forward_host": "www.example.faketld"},
        {"port": 8443, "interface": "127.0.0.1", "forward_host_ssl": "www.example.faketld"},
    ]
</code></pre>

<p>This configuration will cause Pappy to open a port on 8080 that will accept connections normally and a port on 8443 which will accept SSL connections. The forward_host setting tells Pappy to redirect any requests sent to the port to the given host. It will also update the request’s host header. forward_host_ssl does the same thing, but it listens for SSL connections and forces the connection to use SSL.</p>

<p>Or if you’re going to YOLO it do the same thing then listen on port 80/443 directly. I do not suggest you do this.</p>

<pre><code>"proxy_listeners": [
        {"port": 80, "interface": "127.0.0.1", "forward_host": "www.example.faketld"},
        {"port": 443, "interface": "127.0.0.1", "forward_host_ssl": "www.example.faketld"},
    ]
</code></pre>

<p>Pappy will automatically use this host to make the connection and forward the request to the new server.</p>

<h2><a id="user-content-faq" class="anchor" href="#faq" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>FAQ</h2>

<h3><a id="user-content-i-still-like-burp-but-pappy-looks-interesting-can-i-use-both" class="anchor" href="#i-still-like-burp-but-pappy-looks-interesting-can-i-use-both" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>I still like Burp, but Pappy looks interesting, can I use both?</h3>

<p>Yes! If you don't want to go completely over to Pappy yet, you can configure Burp to use Pappy as an upstream proxy server. That way, traffic will go through both Burp and Pappy and you can use whichever you want to do your testing.</p>

<p>How to have Burp forward traffic through Pappy:</p>

<ol>
<li>Open Burp</li>
<li>Go to <code>Options -&gt; Connections -&gt; Upstream Proxy Servers</code></li>
<li>Click <code>Add</code></li>
<li>Leave <code>Destination Host</code> blank, but put <code>127.0.0.1</code> in <code>Proxy Host</code> and <code>8000</code> into <code>Port</code> (assuming you're using the default listener)</li>
<li>Configure your browser to use Burp as a proxy</li>
</ol>

<h3><a id="user-content-why-does-my-request-have-an-id-of---" class="anchor" href="#why-does-my-request-have-an-id-of---" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Why does my request have an id of <code>--</code>?!?!</h3>

<p>You can't do anything with a request/response until it is decoded and saved to disk. In between the time when a request is decoded and when it's saved to disk, it will have an ID of <code>--</code>. So just wait a little bit and it will get an ID you can use.</p>

<h2><a id="user-content-boring-technical-stuff" class="anchor" href="#boring-technical-stuff" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Boring, Technical Stuff</h2>

<p>I do some stuff to try and keep speed and memory usage to reasonable levels. Unfortunately, things might seem slow in some areas. This is where I try and explain why those exist. Honestly, you probably don't care about this, but I'd rather have it written down and have nobody read it than just leave people in the dark.</p>

<h3><a id="user-content-request-cache--memory-usage" class="anchor" href="#request-cache--memory-usage" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Request Cache / Memory usage</h3>

<p>For performance reasons, Pappy by default will not store every request in memory. The cache will store a certain number of the most recently accessed requests in memory. This means that if you go through all of history, it could be slow (for example running <code>ls a</code> or <code>sm</code>). If you have enough RAM to keep everything in memory, you can set the request cache size to -1 to just keep everything in memory. However, even if the cache size is unlimited, it still won't load a request into memory untill you access it. So if you want to load everything in memory, run <code>ls a</code>.</p>

<p>By default, Pappy will cache 2000 requests. This is kind of heavy, but it's assumed you're doing testing on a reasonably specced laptop. Personally, I live on the edge and use -1 until I run into memory issues.</p>

<h2><a id="user-content-changelog" class="anchor" href="#changelog" aria-hidden="true"><svg aria-hidden="true" class="octicon octicon-link" role="img" version="1.1" viewbox="0 0 16 16"><path d="M4 9h1v1h-1c-1.5 0-3-1.69-3-3.5s1.55-3.5 3-3.5h4c1.45 0 3 1.69 3 3.5 0 1.41-0.91 2.72-2 3.25v-1.16c0.58-0.45 1-1.27 1-2.09 0-1.28-1.02-2.5-2-2.5H4c-0.98 0-2 1.22-2 2.5s1 2.5 2 2.5z m9-3h-1v1h1c1 0 2 1.22 2 2.5s-1.02 2.5-2 2.5H9c-0.98 0-2-1.22-2-2.5 0-0.83 0.42-1.64 1-2.09v-1.16c-1.09 0.53-2 1.84-2 3.25 0 1.81 1.55 3.5 3 3.5h4c1.45 0 3-1.69 3-3.5s-1.5-3.5-3-3.5z"/></svg></a>Changelog</h2>

<p>The boring part of the readme</p>

<ul>
<li>0.2.7

<ul>
<li>boring unit tests</li>
<li>should make future releases more stable I guess</li>
<li>Support for upstream SOCKS servers</li>
<li><code>print_params</code> command</li>
<li><code>inv</code> filter</li>
<li><code>param_info</code> command</li>
<li>Filters by request/response only headers/body</li>
<li>Transparent host redirection</li>
<li>Some easier to type aliases for common commands</li>
</ul></li>
<li>0.2.6

<ul>
<li>Fix pip being dumb</li>
<li><code>watch</code> command to watch requests/responses in real time</li>
<li>Added <code>pp[qs] form &lt;id&gt;</code> to print POST data</li>
<li>Bugfixes</li>
</ul></li>
<li>0.2.5

<ul>
<li>Requests sent with repeater now are given <code>repeater</code> tag</li>
<li>Add ppq and pps commands</li>
<li>Look at the pretty prompt</li>
<li>Bugfixes</li>
</ul></li>
<li>0.2.4

<ul>
<li>Add command history saving between sessions</li>
<li>Add html encoder/decoder</li>
<li>All the bugs were fixed so I added some more for 0.2.5</li>
</ul></li>
<li>0.2.3

<ul>
<li>Decoder functions</li>
<li>Add <code>merge</code> command</li>
<li>Bugfixes</li>
</ul></li>
<li>0.2.2

<ul>
<li>COLORS</li>
<li>Performance improvements</li>
<li>Bugfixes (duh)</li>
</ul></li>
<li>0.2.1

<ul>
<li>Improve memory usage</li>
<li>Tweaked plugin API</li>
</ul></li>
<li>0.2.0

<ul>
<li>Lots of refactoring</li>
<li>Plugins</li>
<li>Bugfixes probably</li>
<li>Change prompt to make Pappy look more professional (but it will always be pappy time in your heart, I promise)</li>
<li>Create changelog</li>
<li>Add response streaming if no intercepting macros are active</li>
</ul></li>
<li>0.1.1

<ul>
<li>Start using sane versioning system</li>
<li>Did proxy things</li>
</ul></li>
</ul>
</article>
  </div></body></html>